import { LoaderFunction } from 'react-router-dom';
import { MedicalSpecialty } from '../../entities/medical-specialty';

export const loader: LoaderFunction = async () => {
  const specialties: MedicalSpecialty[] = [
    { code: 'acupuncture', description: 'Acupuntura', icon: 'ThunderboltOutlined' },
    { code: 'allergy-and-immunology', description: 'Alergia e Imunologia', icon: 'MedicineBoxOutlined' },
    { code: 'anesthesiologist', description: 'Anestesiologista', icon: 'SafetyCertificateOutlined' },
    { code: 'angiology', description: 'Angiologia', icon: 'RadarChartOutlined' },
    { code: 'cardiology', description: 'Cardiologia', icon: 'HeartOutlined' },
    { code: 'cardiovascular-surgery', description: 'Cirurgia Cardiovascular', icon: 'ThunderboltOutlined' },
    { code: 'hand-surgery', description: 'Cirurgia de Mão', icon: 'AccountBookFilled' },
    { code: 'head-and-neck-surgery', description: 'Cirurgia de Cabeça e Pescoço', icon: 'MedicineBoxOutlined' },
    {
      code: 'surgery-of-the-digestive-system',
      description: 'Cirurgia do Aparelho Digestivo',
      icon: 'MedicineBoxOutlined',
    },
    { code: 'general-surgery', description: 'Cirurgia Geral', icon: 'ThunderboltOutlined' },
    { code: 'oncological-surgery', description: 'Cirurgia Oncológica', icon: 'MedicineBoxOutlined' },
    { code: 'pediatric-surgery', description: 'Cirurgia Pediátrica', icon: 'MedicineBoxOutlined' },
    { code: 'plastic-surgery', description: 'Cirurgia Plástica', icon: 'SmileOutlined' },
    { code: 'thoracic-surgery', description: 'Cirurgia Torácica', icon: 'MedicineBoxOutlined' },
    { code: 'vascular-surgery', description: 'Cirurgia Vascular', icon: 'MedicineBoxOutlined' },
    { code: 'medical-clinic', description: 'Clínica Médica', icon: 'MedicineBoxOutlined' },
    { code: 'coloproctology', description: 'Coloproctologia', icon: 'MedicineBoxOutlined' },
    { code: 'dermatology', description: 'Dermatologia', icon: 'SkinOutlined' },
    { code: 'endocrinology-and-metabology', description: 'Endocrinologia e Metabologia', icon: 'MedicineBoxOutlined' },
    { code: 'endoscopy', description: 'Endoscopia', icon: 'MedicineBoxOutlined' },
    { code: 'gastroenterology', description: 'Gastroenterologia', icon: 'MedicineBoxOutlined' },
    { code: 'medical-genetics', description: 'Genética Médica', icon: 'AccountBookFilled' },
    { code: 'geriatrics', description: 'Geriatria', icon: 'MedicineBoxOutlined' },
    { code: 'gynecology-and-obstetrics', description: 'Ginecologia e Obstetrícia', icon: 'WomanOutlined' },
    { code: 'hematology-and-hemotherapy', description: 'Hematologia e Hemoterapia', icon: 'MedicineBoxOutlined' },
    { code: 'homeopathy', description: 'Homeopatia', icon: 'MedicineBoxOutlined' },
    { code: 'infectology', description: 'Infectologia', icon: 'MedicineBoxOutlined' },
    { code: 'mastology', description: 'Mastologia', icon: 'MedicineBoxOutlined' },
    { code: 'emergency-medicine', description: 'Medicina de Emergência', icon: 'WarningOutlined' },
    {
      code: 'family-and-community-medicine',
      description: 'Medicina de Família e Comunidade',
      icon: 'UsergroupAddOutlined',
    },
    { code: 'occupational-medicine', description: 'Medicina do Trabalho', icon: 'AccountBookFilled' },
    { code: 'traffic-medicine', description: 'Medicina de Tráfego', icon: 'CarOutlined' },
    { code: 'sports-medicine', description: 'Medicina Esportiva', icon: 'TrophyOutlined' },
    {
      code: 'physical-medicine-and-rehabilitation',
      description: 'Medicina Física e Reabilitação',
      icon: 'MedicineBoxOutlined',
    },
    { code: 'intensive-care-medicine', description: 'Medicina Intensiva', icon: 'ThunderboltOutlined' },
    {
      code: 'legal-medicine-and-medical-expertise',
      description: 'Medicina Legal e Perícia Médica',
      icon: 'SafetyCertificateOutlined',
    },
    { code: 'nuclear-medicine', description: 'Medicina Nuclear', icon: 'MedicineBoxOutlined' },
    {
      code: 'preventive-and-social-medicine',
      description: 'Medicina Preventiva e Social',
      icon: 'MedicineBoxOutlined',
    },
    { code: 'nephrology', description: 'Nefrologia', icon: 'MedicineBoxOutlined' },
    { code: 'neurosurgery', description: 'Neurocirurgia', icon: 'MedicineBoxOutlined' },
    { code: 'neurology', description: 'Neurologia', icon: 'AccountBookFilled' },
    { code: 'nutrilogy', description: 'Nutrologia', icon: 'MedicineBoxOutlined' },
    { code: 'ophthalmology', description: 'Oftalmologia', icon: 'EyeOutlined' },
    { code: 'clinical-oncology', description: 'Oncologia Clínica', icon: 'MedicineBoxOutlined' },
    { code: 'orthopedics-and-traumatology', description: 'Ortopedia e Traumatologia', icon: 'MedicineBoxOutlined' },
    { code: 'otorhinolaryngology', description: 'Otorrinolaringologia', icon: 'MedicineBoxOutlined' },
    { code: 'pathology', description: 'Patologia', icon: 'MedicineBoxOutlined' },
    {
      code: 'clinical-pathology-laboratory-medicine',
      description: 'Patologia Clínica/Medicina Laboratorial',
      icon: 'MedicineBoxOutlined',
    },
    { code: 'pediatrics', description: 'Pediatria', icon: 'AccountBookFilled' },
    { code: 'pneumology', description: 'Pneumologia', icon: 'AccountBookFilled' },
    { code: 'psychiatry', description: 'Psiquiatria', icon: 'MedicineBoxOutlined' },
    {
      code: 'radiology-and-diagnostic-imaging',
      description: 'Radiologia e Diagnóstico por Imagem',
      icon: 'CameraOutlined',
    },
    { code: 'radiotherapy', description: 'Radioterapia', icon: 'MedicineBoxOutlined' },
    { code: 'rheumatology', description: 'Reumatologia', icon: 'MedicineBoxOutlined' },
    { code: 'urology', description: 'Urologia', icon: 'MedicineBoxOutlined' },
  ];
  return specialties;
};
